---
title: "Proposta do Livro"
author: Eu
lang: pt-br
format: html
---

Ideia de estrutura para o livro *Probabilidade, Inferência e Estatística na base da Conversa, do Desenho e da Matemática -- um livro básico* (título provisório)

## Conteúdo que intento desenvolver

As listas das seções a seguir são a ideia das divisões que vou usar, cujos tópicos de nível 1 serão os capítulos, de nível 2 serão seções e assim por diante. As próprias seções serão as partes (ou volumes?) do livro

### Parte 1: ***LEIA-ME*** ou então o livro não fará sentido {#sec-leia-me}

### Parte 2: ***PROBABILIDADE*** ou "como quantificar espectativas de forma matemática com coerência e consisitência" {#sec-probabilidade}

### Parte 3: ***INFERÊNCIA*** ou "como escolher no que acreditar em face a evidências empíricas" {#sec-inferencia}

1. Inferência
  1. O que é inferência: dedução *versus* indução
  1. O que seria então uma inferência *estatística*?
    2. O que é *Estatística*, a área de conhecimento?
      1. O que é esse troço que chamamos hoje de *Estatística*?
      2. Origens históricas da Estatística e sua evolução ao longo do tempo
    1. Porquê entender inferência estatística?
  1. Um panorama das algumas abordagens atuais de como fazer inferências estatísticas
    1. Inferência classica
    2. Inferência bayesiana
    3. Existe inferência fora da Estatística?
      1. Estatística descritiva: inferência sem estatística (por mais estranho que pareça)
      1. Redes neurais
      2. Algoritmos vindos da Computação, da Biologia e outras áreas de conhecimento que ainda não tenham sido formalizadas pela Estatística
  2. Teoria da decisão *versus* teoria de jogos: o divisor de águas entre a inferência clássica e inferência bayesiana
2. Inferência clássica
3. Inferência bayesiana

### Parte 4: ***MÉTODOS*** ou "como fazer as paradas" {#sec-metodos}

1. A matemática por trás dos métodos
  1. Clássicos
  2. Bayesianos
2. A computação por trás dos métodos
  1. Clássicos
  2. Bayesianos
3. Mão na massa
  1. FOSS: Free Open Source Software
  1. R
  2. JASP

### Apêndices {#sec-apendices}

1. Jogos versus Decisão
1. Teoria da Decisão
2. Teoria de Jogos


## Não posso esquecer {#sec-nao-posso-esquecer}

### Razão *versus* emoção? Nope: tudo é cognição 

### exercícios

#### explicações

#### como implementar
